import random
import time
import traceback
from typing import Optional

from loguru import logger

from neurons.config import MissingApiKeyError
from neurons.config.clients import MissingResponseError
from neurons.validator.utils.corcel import call_corcel
from neurons.validator.utils.openai import create_completion_request


def get_random_creature():
    return random.choice(
        [
            # Real animals
            "cat",
            "dog",
            "elephant",
            "lion",
            "butterfly",
            "eagle",
            "dolphin",
            "snake",
            "octopus",
            "panda",
            "giraffe",
            "kangaroo",
            "penguin",
            "parrot",
            "tiger",
            "bear",
            "rabbit",
            "turtle",
            "fox",
            "owl",
            "wolf",
            "koala",
            "rhino",
            "hippopotamus",
            "cheetah",
            "gorilla",
            "sloth",
            "platypus",
            "ostrich",
            "flamingo",
            "chameleon",
            "jellyfish",
            "narwhal",
            "axolotl",
            # Mythical creatures
            "dragon",
            "unicorn",
            "phoenix",
            "mermaid",
            "centaur",
            "griffin",
            "werewolf",
            "fairy",
            "goblin",
            "minotaur",
            "pegasus",
            "kraken",
            "basilisk",
            "chimera",
            "hydra",
            "banshee",
            "yeti",
            "sasquatch",
            "leprechaun",
            "cyclops",
            "siren",
            "harpy",
            "kitsune",
            "wendigo",
            "thunderbird",
            "jackalope",
            # Humans and human-like
            "human",
            "man",
            "woman",
            "girl",
            "boy",
            "cyborg",
            "android",
            "hologram",
            "clone",
            "mutant",
            "superhero",
            "wizard",
            "witch",
            "ninja",
            "samurai",
            "astronaut",
            "time traveler",
            # Futuristic and sci-fi creatures
            "robot",
            "drone",
            "nanobot swarm",
            "AI construct",
            "living spaceship",
            "energy being",
            "interdimensional entity",
            "quantum lifeform",
            "hive mind",
            "plasma creature",
            "shapeshifter",
            "techno-organic hybrid",
            "psionic entity",
            "silicon-based lifeform",
            "gravitational anomaly",
            "temporal paradox being",
            "dark matter organism",
            "antimatter construct",
            "bio-mechanical symbiote",
            "sentient nebula",
            "living planet",
            "crystalline intelligence",
            "multidimensional being",
            "nanotech collective",
            "wormhole dweller",
            "stellar consciousness",
            "quantum ghost",
            "virtual reality avatar",
            "galactic superorganism",
            "singularity entity",
        ]
    )


def get_random_perspective():
    return random.choice(
        [
            "aerial",
            "close-up",
            "panoramic",
            "microscopic",
            "bird's-eye",
            "worm's-eye",
            "fisheye",
            "top-down",
            "side-view",
            "rear-view",
            "isometric",
            "first-person",
            "third-person",
            "macro",
            "wide-angle",
            "telephoto",
            "tilted",
            "skewed",
            "distorted",
            "flipped",
            "mirrored",
            "kaleidoscopic",
            "cross-section",
            "cutaway",
            "translucent",
            "x-ray",
            "thermal",
            "infrared",
            "ultraviolet",
            "low-angle",
            "high-angle",
        ]
    )


def get_random_adjective():
    return random.choice(
        [
            # Emotions and personalities
            "happy",
            "sad",
            "excited",
            "tired",
            "hungry",
            "playful",
            "curious",
            "brave",
            "anxious",
            "confident",
            "shy",
            "outgoing",
            "grumpy",
            "cheerful",
            "melancholic",
            "euphoric",
            "apathetic",
            "passionate",
            "stoic",
            "empathetic",
            # Appearances
            "majestic",
            "radiant",
            "vibrant",
            "shiny",
            "colorful",
            "rusty",
            "old",
            "new",
            "large",
            "small",
            "tall",
            "short",
            "wide",
            "narrow",
            "thick",
            "thin",
            "smooth",
            "rough",
            "sleek",
            "weathered",
            "pristine",
            "disheveled",
            "glamorous",
            "scruffy",
            # Atmospheres and qualities
            "enchanted",
            "mysterious",
            "ethereal",
            "serene",
            "bustling",
            "whimsical",
            "luminous",
            "enigmatic",
            "tranquil",
            "chaotic",
            "harmonious",
            "discordant",
            "sublime",
            "grotesque",
            "surreal",
            "mundane",
            "extraordinary",
            "quotidian",
            # Sensory descriptors
            "loud",
            "quiet",
            "fragrant",
            "pungent",
            "sweet",
            "bitter",
            "soft",
            "hard",
            "squishy",
            "brittle",
            "slimy",
            "fluffy",
            "prickly",
            "silky",
            "coarse",
            # Abstract concepts
            "ephemeral",
            "eternal",
            "temporal",
            "spatial",
            "conceptual",
            "abstract",
            "concrete",
            "relative",
            "absolute",
            "quantum",
            "metaphysical",
            "empirical",
            # Technology and science
            "digital",
            "analog",
            "cybernetic",
            "bionic",
            "quantum",
            "nanotechnological",
            "holographic",
            "virtual",
            "augmented",
            "synthetic",
            "organic",
            "genetically-modified",
            # Environmental
            "verdant",
            "arid",
            "tropical",
            "arctic",
            "volcanic",
            "subterranean",
            "cosmic",
            "terrestrial",
            "aquatic",
            "aerial",
            "urban",
            "rural",
            "sylvan",
            "desert",
            # Fantastical
            "magical",
            "cursed",
            "blessed",
            "spectral",
            "otherworldly",
            "eldritch",
            "fae",
            "arcane",
            "mythical",
            "legendary",
            "supernatural",
            "paranormal",
            # Time-related
            "ancient",
            "futuristic",
            "timeless",
            "contemporary",
            "vintage",
            "avant-garde",
            "retro",
            "prehistoric",
            "primordial",
            "nascent",
            "eternal",
            "evanescent",
            # Intensity and scale
            "microscopic",
            "colossal",
            "gargantuan",
            "minuscule",
            "titanic",
            "infinitesimal",
            "monumental",
            "trivial",
            "epic",
            "modest",
            "overwhelming",
            "subtle",
            # Unusual and evocative
            "iridescent",
            "effervescent",
            "kaleidoscopic",
            "labyrinthine",
            "gossamer",
            "phantasmagorical",
            "incandescent",
            "pellucid",
            "ineffable",
            "tenebrous",
            "coruscating",
            "sempiternal",
            "mercurial",
            "numinous",
            "chimerical",
        ]
    )


def get_random_style():
    return random.choice(
        [
            # Portraits
            "warm portrait",
            "old man portrait",
            "kodak portrait",
            "closeup portrait",
            "happy portrait",
            "noir portrait",
            "vintage 1940s portrait",
            "sepia-toned portrait",
            "dreamy soft focus portrait",
            "ethereal portrait",
            "surreal fantasy portrait",
            "chiaroscuro lighting portrait",
            "high-contrast portrait",
            "vibrant contemporary portrait",
            "fashion magazine portrait",
            "digital oil painting portrait",
            "film noir-inspired portrait",
            # Photography styles
            "long exposure",
            "double exposure effect",
            "vaporwave aesthetic",
            "cyberpunk photoshoot",
            "luxury product",
            "glamorous editorial photography",
            "architectural photography",
            "macro photography",
            "tilt-shift photography",
            "fish-eye lens photography",
            "cinematic photography",
            "pastel film photography",
            "high grain black and white photography",
            "infrared photography",
            "halftone photography",
            "hdr photography",
            # Color schemes & effects
            "sepia",
            "monochrome",
            "duotone",
            "split tone",
            "pastel color palette",
            "neon color palette",
            "high contrast",
            "low contrast",
            "high saturation",
            "desaturated tones",
            "gradient background",
            "dark moody colors",
            "soft warm tones",
            "cold blue hues",
            "golden hour lighting",
            "sunset colors",
            "muted earth tones",
            # Time periods & movements
            "1940s",
            "1950s",
            "1960s",
            "1970s",
            "1980s retro",
            "1990s grunge",
            "art deco",
            "baroque style",
            "renaissance style",
            "impressionist style",
            "surrealist style",
            "futurist style",
            "modernism",
            "postmodernism",
            "cubism",
            "abstract expressionism",
            "minimalism",
            "pop art",
            "bauhaus design",
            "psychedelic",
            "dada",
            "gothic style",
            "victorian style",
            # Art techniques & effects
            "watercolor",
            "oil painting",
            "charcoal drawing",
            "ink illustration",
            "hyperrealistic painting",
            "surreal digital painting",
            "impressionistic brush strokes",
            "line art",
            "pencil sketch",
            "crosshatching",
            "stippling",
            "collage",
            "mixed media",
            "digital painting",
            "pixel art",
            "low-poly style",
            "3d modeling",
            "flat illustration",
            "sticker style",
            "tattoo design",
            "graffiti style",
            "comic book style",
            "graphic novel style",
            "posterized art",
            "screen print",
            # Realism & abstractions
            "photorealistic rendering",
            "hyper-realism",
            "abstract forms",
            "minimalist abstractions",
            "cubist abstraction",
            "geometric design",
            "organic forms",
            "fluid dynamics",
            "fractal patterns",
            "surreal dreamscapes",
            "non-representational art",
            "conceptual art",
            "expressionist colors",
            "emotional brush strokes",
            "visual metaphors",
            # Special effects & lighting
            "glitch effect",
            "lens flare",
            "halation effect",
            "bloom lighting",
            "backlighting",
            "bokeh background",
            "soft light diffusion",
            "harsh spotlight",
            "gobo lighting",
            "studio lighting",
            "cinematic lighting",
            "high-key lighting",
            "low-key lighting",
            "shadow play",
            "dynamic lighting",
            "color grading",
            "gothic shadows",
            # Human emotions & themes
            "joyful celebration",
            "melancholic mood",
            "tranquil peace",
            "intense passion",
            "whimsical daydream",
            "pensive contemplation",
            "heroic strength",
            "subdued melancholy",
            "yearning desire",
            "playful innocence",
            "nostalgic reverie",
            "empowered determination",
            "solitary reflection",
            "humble acceptance",
            "spiritual enlightenment",
            "rebellious defiance",
            "quiet resilience",
            "enduring perseverance",
        ]
    )


def get_random_object():
    return random.choice(
        [
            # Everyday items
            "book",
            "pen",
            "phone",
            "camera",
            "guitar",
            "bicycle",
            "car",
            "cup",
            "chair",
            "table",
            "umbrella",
            "hammer",
            "scissors",
            "knife",
            "spoon",
            "fork",
            "paintbrush",
            "vase",
            "clock",
            "globe",
            "telescope",
            "lamp",
            "backpack",
            "wallet",
            "keys",
            "headphones",
            "sunglasses",
            "watch",
            "hat",
            "scarf",
            "shoes",
            "coat",
            "blanket",
            "pillow",
            "toothbrush",
            "comb",
            "mirror",
            # Electronics and technology
            "laptop",
            "tablet",
            "smartwatch",
            "drone",
            "robot vacuum",
            "3D printer",
            "virtual reality headset",
            "smart speaker",
            "electric car",
            "solar panel",
            "satellite dish",
            "microchip",
            "holographic projector",
            "quantum computer",
            "nanobot injector",
            "brain-computer interface",
            "teleportation pad",
            # Magical and mystical objects
            "crystal",
            "tome",
            "amulet",
            "scepter",
            "chalice",
            "orb",
            "locket",
            "wand",
            "staff",
            "grimoire",
            "rune stone",
            "tarot deck",
            "dreamcatcher",
            "crystal ball",
            "enchanted mirror",
            "phoenix feather",
            "dragon egg",
            "invisibility cloak",
            "time turner",
            "philosopher's stone",
            "elixir of life",
            # Art and decoration
            "tapestry",
            "sculpture",
            "painting",
            "photograph",
            "mosaic",
            "stained glass window",
            "pottery",
            "wood carving",
            "bronze statue",
            "holographic art installation",
            "kinetic sculpture",
            "digital art frame",
            "bonsai tree",
            "terrarium",
            # Tools and instruments
            "microscope",
            "stethoscope",
            "compass",
            "abacus",
            "sextant",
            "sundial",
            "astrolabe",
            "barometer",
            "kaleidoscope",
            "periscope",
            "geiger counter",
            "seismograph",
            "spectroscope",
            "particle accelerator",
            "gravity manipulator",
            # Transportation
            "hoverboard",
            "jetpack",
            "flying car",
            "submarine",
            "space shuttle",
            "time machine",
            "interdimensional portal generator",
            "teleporter",
            "anti-gravity boots",
            "wormhole stabilizer",
            # Unusual or conceptual objects
            "perpetual motion machine",
            "infinity mirror",
            "klein bottle",
            "mobius strip",
            "tesseract",
            "schrodinger's box",
            "pandora's box",
            "mystery box",
            "quantum entanglement visualizer",
            "dark matter container",
            "antimatter bomb",
            # Body parts (as per original list)
            "human face",
            "cybernetic eye",
            "bionic arm",
            "artificial heart",
            "synthetic skin",
            "memory implant",
            "neural interface",
            # Abstract concepts (for more creative applications)
            "idea",
            "memory",
            "dream",
            "emotion",
            "thought",
            "consciousness",
            "quantum superposition",
            "parallel universe",
            "alternate timeline",
        ]
    )


def get_random_background():
    return random.choice(
        [
            # Space and futuristic settings
            "spaceship",
            "near Earth orbit",
            "futuristic city",
            "city of 2033",
            "Mars colony",
            "lunar base",
            "space station",
            "asteroid mining facility",
            "interstellar void",
            "wormhole",
            "alien planet",
            "Dyson sphere",
            "quantum realm",
            "cyberpunk metropolis",
            "post-apocalyptic wasteland",
            "terraformed Venus",
            "Martian canyon",
            "Jovian cloud city",
            "Titan methane sea",
            "Pluto research outpost",
            # Natural environments
            "beach",
            "mountains",
            "countryside",
            "park",
            "forest",
            "cave",
            "island",
            "desert",
            "underwater",
            "sky",
            "garden",
            "river",
            "lake",
            "ocean",
            "cliff face",
            "glacier",
            "volcanic landscape",
            "coral reef",
            "savannah",
            "rainforest",
            "tundra",
            "geothermal area",
            "mangrove swamp",
            "salt flat",
            "canyon",
            "fjord",
            "archipelago",
            "oasis",
            # Urban and man-made environments
            "city",
            "library",
            "cafe",
            "bedroom",
            "castle",
            "ruins",
            "stadium",
            "mall",
            "factory",
            "farm",
            "school",
            "hospital",
            "airport",
            "train station",
            "bridge",
            "tunnel",
            "highway",
            "skyscraper",
            "underground bunker",
            "submarine",
            "cruise ship",
            "theme park",
            "museum",
            "art gallery",
            "concert hall",
            "university campus",
            "botanical garden",
            "zoo",
            "aquarium",
            "observatory",
            "lighthouse",
            "wind farm",
            "solar power plant",
            # Historical settings
            "ancient Rome",
            "medieval village",
            "Victorian London",
            "Wild West town",
            "1920s speakeasy",
            "World War II battlefield",
            "ancient Egyptian temple",
            "Mayan pyramid",
            "Viking longhouse",
            "Renaissance fair",
            "Silk Road oasis",
            "Feudal Japanese castle",
            "Stone Age cave dwelling",
            # Fantastical locations
            "enchanted forest",
            "dragon's lair",
            "wizard's tower",
            "fairy glade",
            "dwarven mine",
            "elven city",
            "goblin market",
            "floating islands",
            "underwater kingdom",
            "cloud castle",
            "crystal cavern",
            "phoenix nest",
            "time vortex",
            "parallel dimension",
            "dream realm",
            "spirit world",
            # Microscopic and macroscopic views
            "inside a human cell",
            "on a strand of DNA",
            "atom's electron cloud",
            "neuron synapse",
            "blood vessel",
            "inside a computer chip",
            "galactic core",
            "black hole event horizon",
            "nebula",
            "quasar",
            "dark matter filament",
            # Abstract and conceptual spaces
            "mindscape",
            "virtual reality construct",
            "data stream",
            "memory palace",
            "collective unconscious",
            "alternate timeline",
            "multiverse nexus",
            "conceptual plane",
            "mathematical dimension",
            "simulated reality",
        ]
    )


def generate_story_prompt() -> str:
    random.seed(int(time.time()))
    random_adjective = get_random_adjective()
    random_background = get_random_background()
    random_creature = get_random_creature()
    random_object = get_random_object()
    random_perspective = get_random_perspective()
    random_style = get_random_style()

    to_return: str = (
        "You are an image prompt generator. "
        "Your purpose is to generate a single, "
        "short story that can be used as a prompt for Dalle-3. "
        "Please ensure that the story is creative, "
        "visually descriptive, and coherent. "
        "The story should be less than 30 words. "
        "Avoid using any additional elements or deviating from "
        "the specified creature, adjective, object, and background."
        "Do not ouput the prompt but rather create your own."
        "The story **must** incorporate the following elements:\n\n"
        f"- Background: {random_background}\n"
    )

    if random.random() > 0.15:
        to_return += f"- Creature: {random_creature}\n"
        to_return += f"- Adjective: {random_adjective}\n"

    if random.random() > 0.85:
        to_return += f"- Object: {random_object}\n"

    if random.random() > 0.85:
        to_return += f"- Perspective: {random_perspective}\n\n"

    if random.random() > 0.85:
        to_return += f"- Style: {random_style}\n\n"

    to_return += "Do not output the above elements, only the resultant story."

    return to_return


async def generate_random_prompt(
    model: str = "gpt-4",
    prompt: Optional[str] = None,
) -> Optional[str]:
    """Generate a random prompt using available services with fallback"""
    if not prompt:
        prompt = generate_story_prompt()

    services = [
        ("openai", lambda p: create_completion_request(model=model, prompt=p)),
        ("corcel", lambda p: call_corcel(p)),
    ]

    for name, service in services:
        try:
            response = await service(prompt)
            if response and not response.startswith("{"):
                return response.replace('"', "").strip()
        except MissingApiKeyError:
            logger.debug(f"Skipping {name} due to missing API key")
        except MissingResponseError:
            logger.debug(f"Skipping {name} due to no response")
        except Exception:
            logger.error(f"Error with {name}: {traceback.format_exc()}")
            continue

    return None
